#include "common-transfer-methods.dl"

#define TaintSourceMethodPattern(pattern) \
  TaintSourceMethod("default", method) :- \
    isMethod(method), \
    match(pattern, method)

#define LeakingSinkMethodPattern(n, pattern) \
  LeakingSinkMethodArg("default", n, method) :- \
    isMethod(method), \
    match(pattern, method)


TaintSourceMethodPattern("<java.io.BufferedReader: java.lang.String readLine\(\)>").
LeakingSinkMethodPattern(0, "<java.io.Print.*: void println\(.*\)>").
